

module.exports = {
  AdminUser: require('./admin_user'),
  Agent: require('./agent'),
  Article: require('./article'),
  Answer: require('./answer'),
  ArticleCategory: require('./articleCategory'),
  City: require('./city'),
  ClaimListing: require('./claimListing'),
  Comment: require('./comment'),
  Contact: require('./contact'),
  EmailList: require('./email_list'),
  Firm: require('./firm'),
  Log: require('./log'),
  LicenseVerification: require('./licenseVerification'),
  Offshore: require('./offshore'),
  Review: require('./review'),
  Role: require('./role'),
  Resource: require('./resource'),
  ResourceCategory: require('./resourceCategory'),
  Sponsor: require('./sponsor'),
  State: require('./state'),
  Question: require('./question'),
  QuestionCategory: require('./questionCategory'),
  User: require('./user'),
  Verification: require('./verification'),
}
