## to use this file you can install Rest Io vs code plugin

POST  http://localhost:3000/api/login HTTP/1.1
content-type: application/json

{
    "email": "ekeh.wisdom@gmail.com",
    "password": "password"
}

###

POST  http://localhost:3000/api/register HTTP/1.1
content-type: application/json

{
    "email": "abc@d.com",
    "password": "password",
    "firstName": "sdfghj",
    "lastName": "Dsghgdf",
    "subscribeToNewsletter": true
}

###

 

POST  http://localhost:3000/api/review HTTP/1.1
content-type: application/json

{
    "email": "ekeh.wisdom@gmail.com",
    "body": "asdhfajfd adhjdghjh",
    "title": "sdfdffdf",
    "firstName": "sdfghj",
    "lastName": "Dsghgdf",
    "rating": 4,
    "agent": "5ff4913a99f914d7a47aa605"
}

###

POST  http://localhost:3000/api/claim-listing/5ff4913a99f914d7a47aa605 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiN2EzYTExYjVjYWE4ZDY2ZGU4ZGU2YmY4YzAyMDE1ZTYwMjJmZTUxNzBlYWU1NTJiY2Q4MGY3NDgwMjBjMGM5NjIzZTFkZWRjMTA2NGRiMjg2YzM0MjI1MDU1NGYwYzhkYzFmYjhhMTBkZDI5YjZlMTFiNTBmMTIwM2MzYTg2ODVlOGE0NTljOGU2NWJmYmY4NmFiNDg5ODJmN2JlMGYxZDNhZWQ0OWI3NDEzYzUzODYyMTI0MDMyZTM2NWYzYmRiM2IxNmRhNDNmY2VjZWFiNjc2MmExZjZmMmU3ZThjZjNiNDU0NmQyYmJmYzU1NWY2OTk4MGVkYzhkMTRkMzU4MmM2ZjU0MmVlNWQwYTZiY2RlMGQwZWY2MGU1OWIwZDY2MmI3OTYzNmRlZDY4MTZlODZlNzA1ZjJmYTk2NTBlOWFhZmQ5M2MzMzQ3YThjOTEyZDUiLCJpc3MiOiJjb20ud2lzZW1pbmRzc29sdXRpb25zIiwiYXVkIjoiVVNFUiIsImlhdCI6MTYwOTkyNzk2MywiZXhwIjoxNjA5OTcxMTYzfQ.5ew78L6gXGHbHXPxrohtMdQeNCoZ_kfSjaKB3L1yfZU

{
     "jobRole": "dvsfbfhg",
      "companySize": "dsgfhtfg",
      "companyName": "SDFgfhgdfag",
      "companyRevenue": "Sdgfmnsasf",
      "organizationType": "Sgfdhfsdfasd",
      "annualTax": "SFgdfhsgdfagsd"
}

###

POST  http://localhost:3000/api/ask HTTP/1.1
content-type: application/json

{
    "email": "ekeh.wisdom@gmail.com",
    "body": "asdhfajfd adhjdghjh",
    "title": "sdfdffdf",
    "firstName": "sdfghj",
    "lastName": "Dsghgdf",
    "phone": "09902836879233",
    "category": "5ff49bf3353419e7d6044c64"
}

###

POST  http://localhost:3000/api/answer HTTP/1.1
content-type: application/json

{
    "message": "Dsghghjgjhggdf",
    "question": "5ff7878fde0fbc2a277699e2"
}

###

POST  http://localhost:3000/api/article/comment/5feb11d015b6e0de7d4f9894 HTTP/1.1
content-type: application/json

{
    "message": "Dsghghjgjhggdf",
     "email": "ekeh.wisdom@gmail.com",
    "body": "asdhfajfd adhjdghjh",
    "title": "sdfdffdf",
    "firstName": "sdfghj",
    "lastName": "Dsghgdf",
    "phone": "09902836879233" 
}


###

POST  http://localhost:3000/api/offshore HTTP/1.1
content-type: application/json

{
    "message": "Dsghghjgjhggdf",
     "email": "ekeh.wisdom@gmail.com",
    "body": "asdhfajfd adhjdghjh",
    "title": "sdfdffdf",
    "firstName": "sdfghj",
    "lastName": "Dsghgdf",
    "phone": "09902836879233"
}

###
POST  http://localhost:3000/api/licence HTTP/1.1
content-type: application/json

{
    "message": "Dsghghjgjhggdf",
     "email": "ekeh.wisdom@gmail.com",
    "body": "asdhfajfd adhjdghjh",
    "title": "sdfdffdf",
    "firstName": "sdfghj",
    "lastName": "Dsghgdf",
    "phone": "09902836879233"
}


###
POST  http://localhost:3000/api/upgrade-account HTTP/1.1
content-type: application/json

# {
#     "message": "Dsghghjgjhggdf",
#      "email": "ekeh.wisdom@gmail.com",
#     "body": "asdhfajfd adhjdghjh",
#     "title": "sdfdffdf",
#     "firstName": "sdfghj",
#     "lastName": "Dsghgdf",
#     "phone": "09902836879233"
# }



###

POST  http://localhost:3000/api/listing-request HTTP/1.1
content-type: application/json

{
    "message": "Dsghghjgjhggdf",
     "email": "ekeh.wisdom@gmail.com",
    "body": "asdhfajfd adhjdghjh",
    "title": "sdfdffdf",
    "firstName": "sdfghj",
    "lastName": "Dsghgdf",
    "phone": "09902836879233" ,
    "zipcode": "3214545" ,
    "city": "3214545" ,
    "state": "3214545" ,
    "licence": "321454543555" ,
    "stateLicenced": "Arizona"

}
